image: "rust:latest"

test:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose --all-features --all
    - cargo test --workspace --verbose -all

pages:
  stage: deploy
  script:
    - cargo doc --no-deps --all-features
    - mkdir public
    - mv target/doc public
  artifacts:
    paths:
      - public
