[package]
name = "tycho"
version = "0.0.6"
authors = ["Sam Huddart <sam.fucked.up@samh.dev>"]
edition = "2018"
description = "A self describing binary format designed around the serde data model."
license="MIT"
documentation="https://docs.rs/tycho"
repository = "https://github.com/samhdev/tycho"
homepage = "https://github.com/samhdev/tycho"

[dependencies]
byteorder = "1.4.2"
serde = "1.0.120"

[dev-dependencies.serde]
version = "1.0.120"
features = ["derive"]