[package]
name = "tycho4"
version = "0.0.1"
authors = ["Sam Huddart <sam02h.huddart@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.2"
serde = "1.0.120"

[dev-dependencies.serde]
version = "1.0.120"
features = ["derive"]