[package]
name = "tycho"
version = "0.0.2"
authors = ["Sam Huddart <sam.fucked.up@samh.dev>"]
edition = "2018"
description = "A self describing binary format designed around the serde data model."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.2"
serde = "1.0.120"

[dev-dependencies.serde]
version = "1.0.120"
features = ["derive"]